### ISSUE TITLE
Missing lib-dynload in macOS builds

### ISSUE THREAD

**Issue by kornholi** [indygreg/python-build-standalone#10]
`install/lib/python3.7/lib-dynload` is missing in the macOS builds, breaking exec_prefix detection:

```
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python 3.7.3 (default, Jun 17 2019, 22:24:24)
[Clang 6.0.1 (tags/RELEASE_601/final)] on darwin
```

Creating an empty directory fixes it, but I wonder if anything else is missing as well? Running 
`build-macos.py` fails for me on macOS 10.14.5, so I couldn't track this down:

```
cpython-macos>  CC='clang' LDSHARED='clang -bundle -undefined dynamic_lookup -L/private/var/folders/jp/gp7mqwc963vc1487847t8b180000gn/T/tmpajyuh1zi/deps/lib   ' OPT='-DNDEBUG -g -fwrapv -O3 -Wall' 	_TCLTK_INCLUDES='' _TCLTK_LIBS='' 	./python.exe -E ./setup.py  build
cpython-macos> running build
cpython-macos> running build_ext
cpython-macos> error: [Errno 2] No such file or directory: '/install/include/python3.7m/pyconfig.h'
cpython-macos> make[1]: *** [sharedmods] Error 1
```

**Comment by indygreg** [comment]
I do not encounter this on my builds.

I think the `exec_prefix` detection being busted might be harmless, as I don't believe we produce any platform specific files? I could be wrong about that.

Are you building with current `master` or what?

**Comment by kornholi** [comment]
Yep, it should be harmless besides the startup warning. You're right about platform specific files, there aren't any in the linux version, but at least the directory's there. 

Yes, `master` doesn't build for me. I tried again today with the 3.7.4 changes, same exact error. I'll try to find some more time to look into it.
