### ISSUE TITLE
Platforms without pgo+lto builds don't get an install_only archive

### ISSUE THREAD

**Issue by meastham** [indygreg/python-build-standalone#104]
Due to (I think) this wildcard: https://github.com/indygreg/python-build-standalone/blob/1dfe9d4186e37bd57c544b09402690e968a225be/.github/workflows/linux.yml#L436

In particular this means there aren't install_only archives for linux aarch64, which is a fairly common platform.

Assuming this isn't intentional, I'd be happy to send a PR to change it.

**Comment by indygreg** [comment]
This will be fixed in the next release: with recent commits in main, all triples that have release artifacts will have a corresponding `install_only.tar.gz` release artifact with the most performant build that is available.
