### ISSUE TITLE
cpython  static version (windows-msvc-static-noopt) does not work on nanoserver

### ISSUE THREAD

**Issue by hemnstill** [indygreg/python-build-standalone#111]
[windows-msvc-static-noopt](https://github.com/indygreg/python-build-standalone/releases/download/20211017/cpython-3.10.0-x86_64-pc-windows-msvc-static-noopt-20211017T1616.tar.zst) does not start silently.

[windows-msvc-shared-pgo](https://github.com/indygreg/python-build-standalone/releases/download/20211017/cpython-3.10.0-x86_64-pc-windows-msvc-shared-pgo-20211017T1616.tar.zst) worked well.

nanoserver version: `mcr.microsoft.com/windows/nanoserver:ltsc2022-amd64`

**Comment by indygreg** [comment]
What's the output? (I'm away from my Windows machine at the moment and don't have a great way to test this.)

**Comment by hemnstill** [comment]
Output is empty, it only return exit code: 53

I will try to add debug information via NanoServerApiScan later.

**Comment by hemnstill** [comment]
nothing to do here anymore


https://github.com/indygreg/python-build-standalone/issues/221
