### ISSUE TITLE
Request for additional `tar.gz` release artifacts

### ISSUE THREAD

**Issue by UebelAndre** [indygreg/python-build-standalone#116]
Would it be possible to get `x86_64-pc-windows-msvc-static-install_only` artifacts? Also, can `tar.gz` artifacts be produced for all available `install_only` python3.8 artifacts?

**Comment by indygreg** [comment]
I just pushed a series of commits that should result in `install_only.tar.gz` archives for all target triples flagged for release, including the Windows static builds.

This is all built into the in-repo release code so the next release should pick things up. I may publish that tomorrow. We'll see...

**Comment by UebelAndre** [comment]
Another release would also be welcomed, whatever is easiest 😄

**Comment by indygreg** [comment]
https://github.com/indygreg/python-build-standalone/releases/tag/20220227 is actively uploading now.

**Comment by UebelAndre** [comment]
Thank you!

**Comment by indygreg** [comment]
Actually, I'm going to republish the artifacts in this release to fix a Windows bug. So please wait a few hours before pinning content digests.

**Comment by UebelAndre** [comment]
Sounds good. Just ping here and I'll repin
