### ISSUE TITLE
Request for re-release of `20200822`

### ISSUE THREAD

**Issue by UebelAndre** [indygreg/python-build-standalone#117]
Would it be possible to get a re-release of https://github.com/indygreg/python-build-standalone/releases/tag/20200822 where the artifacts have matching timestamps?

**Comment by indygreg** [comment]
I'm not super inclined to redo a release from 2020 since it is so old.

Why do you want such an old release?

**Comment by UebelAndre** [comment]
For a python 3.7 interpreter.

**Comment by UebelAndre** [comment]
Actually, https://github.com/bazelbuild/rules_python/pull/654 would solve for the need to alter any existing releases as far as I'm aware. Closing this in favor of that PR. Sorry about the distraction!
