### ISSUE TITLE
Windows runtime dependencies

### ISSUE THREAD

**Issue by jayvdb** [indygreg/python-build-standalone#13]
The README doesnt list the runtime requirements on Windows.  ping @uranusjr, I guess you can help with this?

This is a significant omission contrasting with the care given to the licensing choices and documentation for Linux/macOS.

I guess that the 'standalone' runtime still depends on Microsoft redistributables, which have shrink-wrap licenses that need to be carefully considered, so they should be documented.

Ideally any non-OS runtime dependencies are eliminated where possible.

**Comment by uranusjr** [comment]
From my experience the only runtime dependency is indeed vcredist (if you build with Visual Studio). You can either drop the dll in the distribution with python.exe (with licensing implications), or instruct the user to install it. The tricky part is to install the correct runtime (it needs to match the toolchain’s version and bitness, not the OS’s).
