### ISSUE TITLE
aarch64 Linux version for 3.8.12 / 3.8.13

### ISSUE THREAD

**Issue by mattem** [indygreg/python-build-standalone#135]
Broken out from https://github.com/indygreg/python-build-standalone/issues/118#issuecomment-1197544009
If possible, please provide aarch64 Linux versions of 3.8.12 and 3.8.13 interpreters. Thanks!

**Comment by indygreg** [comment]
I was able to implement this pretty easily. Although I haven't tested the distros that much. So I'm going to call them out as beta in the eventual release notes.

How important is it to have a 3.8.12 artifact? The release automation for this project is already time consuming and I'd have to hack it up to work one-off 3.8.12 artifacts into a release.

Publishing a GitHub release with just the 3.8.12 aarch64 Linux builds should be relatively easy. But doing a regular release with the artifacts for all the target builds will be considerable work that I'd prefer to avoid.

**Comment by mattem** [comment]
Great thanks!

> How important is it to have a 3.8.12 artifact?

It would be great to have a release artifact, a one off is fine. We'd need a release artifact to set for [rules_python users](https://github.com/bazelbuild/rules_python/blob/main/python/versions.bzl#L62). I think previously the 20220227 release was edited to include the aarch64 MacOS version.

Happy to put the release though our test suites to give it some usage.

**Comment by mattem** [comment]
For sure! Not sure I can get a test run patched and done in 12, but I'll start the process asap 👍

**Comment by mattem** [comment]
@indygreg We ran though a few test suites internally and things look good 👍 (they don't test every aspect of the interpreter by any means however).

**Comment by alexeagle** [comment]
Ping on getting a release artifact here :)
