### ISSUE TITLE
Release 20220630: Broken script `bin/python3-config` and `bin/python3.x-config`

### ISSUE THREAD

**Issue by nukemiko** [indygreg/python-build-standalone#136]
The content of `bin/python3-config` is starts with:

```sh
#!/bin/sh
"exec" "$(dirname $0)/python3.10" "$0" "$@"

# Keep this script in sync with python-config.in

exit_with_usage ()
{
    echo "Usage: $0 --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir|--embed"
    exit $1
}
```

The `"exec"` statement will start `"$(dirname $0)/python3.10"` to replace current shell process, but this is a totally shell script, not shell-python combined script. If you don't modify this script, it won't work:

```sh-session
miketsu@Miketsu:/dev/pts/2 → ~/Projects/python-runtime/3.10.5+20220630-x86_64-unknown-linux-gnu-pgo+lto/bin (0)
$ > ./python3-config 
  File "/home/miketsu/Projects/python-runtime/3.10.5+20220630-x86_64-unknown-linux-gnu-pgo+lto/bin/./python3-config", line 64
    --help)
          ^
SyntaxError: unmatched ')'
miketsu@Miketsu:/dev/pts/2 → ~/Projects/python-runtime/3.10.5+20220630-x86_64-unknown-linux-gnu-pgo+lto/bin (1)
$ >
```

After commenting out the line where `"exec"` is:

```sh-session
miketsu@Miketsu:/dev/pts/2 → ~/Projects/python-runtime/3.10.5+20220630-x86_64-unknown-linux-gnu-pgo+lto/bin (1)
$ > ./python3-config --help
Usage: ./python3-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir|--embed
miketsu@Miketsu:/dev/pts/2 → ~/Projects/python-runtime/3.10.5+20220630-x86_64-unknown-linux-gnu-pgo+lto/bin (0)
```

Tested packages:

- [cpython-3.10.5+20220630-i686-unknown-linux-gnu-pgo+lto-full.tar.zst](https://github.com/indygreg/python-build-standalone/releases/download/20220630/cpython-3.10.5+20220630-i686-unknown-linux-gnu-pgo+lto-full.tar.zst)
- [cpython-3.10.5+20220630-x86_64-unknown-linux-gnu-pgo+lto-full.tar.zst](https://github.com/indygreg/python-build-standalone/releases/download/20220630/cpython-3.10.5+20220630-x86_64-unknown-linux-gnu-pgo+lto-full.tar.zst)
- [cpython-3.10.5+20220630-x86_64-unknown-linux-musl-lto-full.tar.zst](https://github.com/indygreg/python-build-standalone/releases/download/20220630/cpython-3.10.5+20220630-x86_64-unknown-linux-musl-lto-full.tar.zst)

**Comment by indygreg** [comment]
Yikes. This is a legit bug with our shebang rewriting. Thanks for the report!
