### ISSUE TITLE
Static test modules

### ISSUE THREAD

**Issue by jayvdb** [indygreg/python-build-standalone#15]
I was surprised to see the test modules are being built in.   Wouldn't that increase the size for no particular benefit?

I didnt see the test suite being run, although I didnt look very hard.

```sh
$ git grep test
..
static-modules.linux64:_ctypes_test _ctypes/_ctypes_test.c -I/tools/deps/lib/libffi-3.2.1/include -lm
static-modules.linux64:_testbuffer _testbuffer.c
static-modules.linux64:_testimportmultiple _testimportmultiple.c
static-modules.linux64:_testmultiphase _testmultiphase.c
static-modules.linux64:_xxtestfuzz _xxtestfuzz/_xxtestfuzz.c _xxtestfuzz/fuzzer.c
static-modules.macos:_ctypes_test _ctypes/_ctypes_test.c -lm
static-modules.macos:_testbuffer _testbuffer.c
static-modules.macos:_testimportmultiple _testimportmultiple.c
static-modules.macos:_testmultiphase _testmultiphase.c
static-modules.macos:_xxtestfuzz _xxtestfuzz/_xxtestfuzz.c _xxtestfuzz/fuzzer.c
```

**Comment by indygreg** [comment]
The test suite is not being run. Although I think it would be useful to include the test modules in the distribution so downstream consumers could potentially run the test suite and verify everything works.

But I'll leave this bug open to track down remaining issues, like whether we want to annotate the test modules in the distribution JSON.

**Comment by jayvdb** [comment]
https://github.com/indygreg/PyOxidizer/issues/152 notes that `_testcapi` is missing.

**Comment by jayvdb** [comment]
Note that CPython `test/test_xxtestfuzz.py` needs module `_xxtestfuzz _xxtestfuzz/_xxtestfuzz.c _xxtestfuzz/fuzzer.c`

**Comment by indygreg** [comment]
I have pushed a bunch of commits to no longer build test extensions as built-ins. The extensions are now built as standalone files and various tests now pass.

I am trying to annotate known test failures and skips at https://python-build-standalone.readthedocs.io/en/latest/status.html. We are completely clean on macOS for CPython 3.7.7 and 3.8.2. Linux still has a few failures. I haven't even gotten to testing musl builds yet. I suspect those will be a disaster....
