### ISSUE TITLE
Patching makesetup

### ISSUE THREAD

**Issue by jayvdb** [indygreg/python-build-standalone#16]
https://github.com/indygreg/python-build-standalone/blob/274f549/pythonbuild/cpython.py#L294 refers to a problem I just hit when trying to use https://github.com/indygreg/python-build-standalone/blob/master/cpython-unix/static-modules.linux64 , in that CPython `makesetup` breaks when Setup.local entries contain `=`.

I am actually trying to setup suitable static builds on Open Build Service, so borrowing only the logic found here, which has been quite useful.

It seems that a bunch of hacks here could be removed by patching `makesetup`.

Upstream issue at https://bugs.python.org/issue37839 , with more details at https://bugs.python.org/issue35184

I've also encountered it on Python 3.7, and the above bpo issues suggest it pre-dates that which would block https://github.com/indygreg/python-build-standalone/issues/8

**Comment by jayvdb** [comment]
fwiw, the 'drop the =1' approach definitely wont be sufficient.  At least `_decimal` blows up badly, and `xxlimited` clearly looks like it also cant be solved that way.

**Comment by indygreg** [comment]
Thanks for the pointers to upstream. I'll try to keep my eye on things.

This issue doesn't appear to be actionable, so closing out.
