### ISSUE TITLE
Docsite suggests `tar -axvf` which is invalid on mac

### ISSUE THREAD

**Issue by thejcannon** [indygreg/python-build-standalone#164]
:wave: Howdy!

Was trying out `tar -axvf path/to/distribution.tar.zstd` as suggested on the docs but got slapped with `tar: Option -a is not permitted in mode -x` on CI. Guess Macs have different cmdline options.

Looks like `-I zstd` is required if you want to make it portable.

**Comment by mitsuhiko** [comment]
I *think* most platforms work with jut `tar xf` at this point.
