### ISSUE TITLE
libedit multibyte character unicode Input

### ISSUE THREAD

**Issue by mitsuhiko** [indygreg/python-build-standalone#169]
`libedit` as compiled into these interpreters hast at least on macOS issues with multibyte characters. If you take the Unicode Snowman `☃` and you paste it into the interpreter, you end up with this:

```python
Python 3.10.9 (main, Dec 20 2022, 19:01:09) [Clang 14.0.3 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> x = "â☃"
>>> x
'â☃'
```

Notice the extra added `â` which appears out of thin air after copy paste. The same happens if you copy paste a word with Umlauts: `"Bälle"` turns into `"BÃälle"`.

I'm not sure if this a bug against cpython/libedit or here but I was _told_ recently that recent libedit versions should no longer have this issue.

**Comment by mitsuhiko** [comment]
Turns out this is still unresolved in libedit as used by CPython. Closing this here.

**Comment by indygreg** [comment]
If you have a link to an upstream issue, feel free to drop it in this issue. I'm curious about why this doesn't work.

We currently link against the libedit provided by macOS. We _might_ be able to build our own libedit if the macOS one doesn't have proper multibyte support.
