### ISSUE TITLE
Next release - ppc64le builds

### ISSUE THREAD

**Issue by sumitd2** [indygreg/python-build-standalone#170]
Hi team,
Can you tell me when is the next release out? I am interested in the ppc64le builds.
Thank you.

**Comment by indygreg** [comment]
I pushed a handful of commits to the ci-test branch in preparation for a release. If CI passes, I may release.

But looking over my notes and open GitHub issues, there are some additional change that might need made. e.g. downgrading DWARF to version 4 for better debugger compatibility.

**Comment by indygreg** [comment]
The 20230507 release assets are uploading now.

**Comment by sumitd2** [comment]
Thank you!
