### ISSUE TITLE
GitHub Actions CI unreliability

### ISSUE THREAD

**Issue by Edward-Knight** [indygreg/python-build-standalone#177]
Looking at the CI results from this week (2023-06-23 – 2023-06-16), I'm seeing some consistent failures.
I've dug into some of them to try and diagnose the problem.

## Failures

* [2023-06-22 Linux](https://github.com/indygreg/python-build-standalone/actions/runs/5344872706)
  * [image (build.cross)](https://github.com/indygreg/python-build-standalone/actions/runs/5344872706/jobs/9689787957#step:4:313)
  * [image (xcb)](https://github.com/indygreg/python-build-standalone/actions/runs/5344872706/jobs/9689788332#step:4:205)
  * [image (xcb.cross)](https://github.com/indygreg/python-build-standalone/actions/runs/5344872706/jobs/9689788507#step:4:313)
* [2023-06-21 Linux](https://github.com/indygreg/python-build-standalone/actions/runs/5333407390)
  * [image (build.cross)](https://github.com/indygreg/python-build-standalone/actions/runs/5333407390/jobs/9663829873#step:4:153)
  * [image (gcc)](https://github.com/indygreg/python-build-standalone/actions/runs/5333407390/jobs/9663829990#step:4:294)
  * [image (xcb.cross)](https://github.com/indygreg/python-build-standalone/actions/runs/5333407390/jobs/9663830215#step:4:169)
* [2023-06-20 Linux](https://github.com/indygreg/python-build-standalone/actions/runs/5321879618)
  * [image (gcc)](https://github.com/indygreg/python-build-standalone/actions/runs/5321879618/jobs/9637548239#step:4:287)
  * [image (xcb.cross)](https://github.com/indygreg/python-build-standalone/actions/runs/5321879618/jobs/9637548521#step:4:1218)
* [2023-06-20 Windows](https://github.com/indygreg/python-build-standalone/actions/runs/5321881110)
  * [build (cpython-3.11, vcvars32.bat, shared-pgo)](https://github.com/indygreg/python-build-standalone/actions/runs/5321881110/jobs/9637618701#step:19:30)
* [2023-05-19 Linux](https://github.com/indygreg/python-build-standalone/actions/runs/5311203281)
  * [image (build.cross)](https://github.com/indygreg/python-build-standalone/actions/runs/5311203281/jobs/9614117932#step:4:155)
  * [image (build)](https://github.com/indygreg/python-build-standalone/actions/runs/5311203281/jobs/9614117777#step:4:207)
  * [image (xcb)](https://github.com/indygreg/python-build-standalone/actions/runs/5311203281/jobs/9614118209#step:4:207)
  * [image (xcb.cross)](https://github.com/indygreg/python-build-standalone/actions/runs/5311203281/jobs/9614118347#step:4:155)
* [2023-05-18 Linux](https://github.com/indygreg/python-build-standalone/actions/runs/5303344730)
  * [image (build.cross)](https://github.com/indygreg/python-build-standalone/actions/runs/5303344730/jobs/9598900103#step:4:717)
  * [image (gcc)](https://github.com/indygreg/python-build-standalone/actions/runs/5303344730/jobs/9598900139#step:4:289)
  * [image (xcb)](https://github.com/indygreg/python-build-standalone/actions/runs/5303344730/jobs/9598900167#step:4:201)
  * [image (xcb.cross)](https://github.com/indygreg/python-build-standalone/actions/runs/5303344730/jobs/9598900209#step:4:697)
* [2023-05-18 Windows](https://github.com/indygreg/python-build-standalone/actions/runs/5303346325)
  * [build (cpython-3.8, vcvars32.bat, static-noopt)](https://github.com/indygreg/python-build-standalone/actions/runs/5303346325/jobs/9598919039#step:19:30)
* [2023-05-17 Linux](https://github.com/indygreg/python-build-standalone/actions/runs/5297857882)
  * [image (build.cross)](https://github.com/indygreg/python-build-standalone/actions/runs/5297857882/jobs/9589882905#step:4:215)
  * [image (gcc)](https://github.com/indygreg/python-build-standalone/actions/runs/5297857882/jobs/9589882955#step:4:287)
  * [image (xcb.cross)](https://github.com/indygreg/python-build-standalone/actions/runs/5297857882/jobs/9589883081#step:4:675)
* [2023-06-16 Linux](https://github.com/indygreg/python-build-standalone/actions/runs/5289343931)
  * [image (gcc)](https://github.com/indygreg/python-build-standalone/actions/runs/5289343931/jobs/9572145053#step:4:146)
  * [image (xcb)](https://github.com/indygreg/python-build-standalone/actions/runs/5289343931/jobs/9572145160#step:4:146)
  * [image (xcb.cross)](https://github.com/indygreg/python-build-standalone/actions/runs/5289343931/jobs/9572145286#step:4:218)

### Linux Failures

The `image (xcb.cross)` job is failing in every workflow sampled, with other image build jobs failing sporadically. It looks like all jobs are failing for the same reasons, and `image (xcb.cross)` just happens to try and pull more packages.
Of the 22 failures, all of them are during apt update or install operations, pulling from snapshot.debian.org. I've broken them down by the error message (although some logs contain multiple errors):
* 503 Backend fetch failed: 9 failures
* Hash Sum mismatch: 6 failures
* 503 Service Unavailable: 3 failures (all on one day)
* 404 NOT FOUND: 2 failures
* The repository does not have a Release file: 2 failures

From my experience with apt and reprepro, I know that:
* Default Ubuntu archives can be slow and do rate limit / IP block
* If the remote repo state is mid-update, clients may experience errors with hashsum mismatches

Since these are "frozen" snapshots, I assume they aren't being updated, so I'm chalking all these failures up to the host being unreliable.

I found this on https://wiki.debian.org/BisectDebian:
> At least as of 2019 snapshot.debian.org blocks access from AWS and has rate-limits for all addresses making installing from snapshots.debian.org unreliable

And the current rules can be seen here: https://salsa.debian.org/dsa-team/mirror/dsa-puppet/-/blob/production/modules/roles/manifests/snapshot_web.pp.

To fix, we could:
* Cache the built images instead of re-building daily
* Find a different mirror
  * I don't know of any mirrors of the snapshots
* Use apt's retry logic
  * We already set `Acquire::Retries "5"` on `build.cross.Dockerfile` and `base.Dockerfile`.
  * We could try setting `Acquire::Queue-Mode "host"` to avoid opening so many connections
    * This would slow down the job, but potentially avoid hitting rate limiting / IP blocking rules
  * May also be worth setting `Debug::Acquire::http` and `Debug::pkgAcquire::Auth` to dig further
* Use a proxy to avoid rate limits for GitHub Action servers

IMO caching the Docker images seems like the way to go, we can use [GitHub's Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) for this.

### Windows Failures

Both Windows jobs failed in the same way in the "Install Cygwin Environment" step:
```
Invoke-WebRequest https://cygwin.com/setup-$platform.exe -OutFile C:\setup.exe
  shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
Invoke-WebRequest : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
```

We're not using the latest version of this Action, but this code looks unchanged.
Looks like a sporadic network failure. It's unclear where exactly the problem is, could potentially be made reliable with a retry mechanism.

## Proposed fixes

* #178
* #179
* cygwin/cygwin-install-action#9

I believe if the above issues are resolved then CI should be reliable.

**Comment by indygreg** [comment]
Thank you very much for doing this research and filing issues to track shoring up CI reliability!

**Comment by Edward-Knight** [comment]
The image caching has sped up the CI times on my fork massively, thanks for fixing those issues @indygreg!

**Comment by Edward-Knight** [comment]
Closing this out as CI is now nice and reliable due to the caches :)
