### ISSUE TITLE
Linux image builds in GitHub Actions could increase use of retry logic and hit snapshot.debian.org less hard

### ISSUE THREAD

**Issue by Edward-Knight** [indygreg/python-build-standalone#178]
This change is designed to help resolve #177, see for more details.

We already set `Acquire::Retries "5"` on `build.cross.Dockerfile` and `base.Dockerfile`.
We could try increasing this, as well as setting `Acquire::Queue-Mode "host"` to avoid opening so many connections.

This would slow down the job, but potentially avoid hitting rate limiting / IP blocking rules. May also be worth setting `Debug::Acquire::http` and `Debug::pkgAcquire::Auth` to dig further.

**Comment by indygreg** [comment]
I haven't seen image build reliability issues in a few months. So going to call this one closed.
