### ISSUE TITLE
Docs site missing last 2 quirks

### ISSUE THREAD

**Issue by thejcannon** [indygreg/python-build-standalone#185]
:wave: I'm looking at https://python-build-standalone.readthedocs.io/en/latest/quirks.html and It seems to be missing:

- https://github.com/indygreg/python-build-standalone/blob/main/docs/quirks.rst#missing-libcryptso1
- https://github.com/indygreg/python-build-standalone/blob/main/docs/quirks.rst#references-to-build-time-paths

Only noticed because I was looking for a link to the latter.

**Comment by indygreg** [comment]
The canonical home of the docs is https://gregoryszorc.com/docs/python-build-standalone/.

I just deleted the outdated Read the Docs mirror to avoid any future confusion.
