### ISSUE TITLE
Missing Python 3.8.18

### ISSUE THREAD

**Issue by kpark-hrp** [indygreg/python-build-standalone#188]
It looks like last round of release included `3.9.18` but not `3.8.18`, which were release together according to https://www.python.org/doc/versions/

Can `3.8.18` be released? Needed for https://github.com/bazelbuild/rules_python/issues/1396

**Comment by indygreg** [comment]
Oops. Looks like we were running versions behind on 3.8 and I upgraded the last release from 3.8.16 -> 3.8.17. What an epic fail on my part.

Commit 8e4eb25f00b45a2a384df1ac0ac53779b5051be3 upgrades to 3.8.18. It will be part of the next release. I'm not sure when that will be.

**Comment by indygreg** [comment]
New release should be posted sometime in the next few hours. Like many releases, timing depends on how much GitHub Actions cooperates.
