### ISSUE TITLE
Enable tzset when x-compiling to linux target

### ISSUE THREAD

**Issue by bcmyers** [indygreg/python-build-standalone#196]
When cross-compiling, `configure` cannot detect if the target system has a working `tzset` function in C. This influences whether or not the compiled python will end up with the `time.tzset` function, which is used by `django` and other important python projects. 

With more and more folks trying to move to arm64 machines in the cloud (since they are often cheaper), it would be nice to have access to `time.tzset` on `aarch64-unknown-linux-gnu`.

Since all linux targets should have a working `tzset` function in C, we should be able to just manually indicate this to the configure script. I've created a PR (#195) that does this.

**Comment by indygreg** [comment]
Closes by #195.
