### ISSUE TITLE
`sys.winver` is `3.1` instead of `3.11`

### ISSUE THREAD

**Issue by ala-ableton** [indygreg/python-build-standalone#199]
I downloaded and extracted https://github.com/indygreg/python-build-standalone/releases/download/20231002/cpython-3.11.6+20231002-i686-pc-windows-msvc-static-install_only.tar.gz, then ran `python.exe -c "import sys; print(sys.winver)"` and it printed `3.1`, instead of the expected `3.11`.
This is because on https://github.com/indygreg/python-build-standalone/blob/main/cpython-windows/build.py#L1525, the Python version gets truncated to 3 characters.

**Comment by indygreg** [comment]
Thanks for the report!

**Comment by ala-ableton** [comment]
Thanks for fixing!
