### ISSUE TITLE
Add armv7-unknown-linux-gnueabihf builds to releases

### ISSUE THREAD

**Issue by fyhertz** [indygreg/python-build-standalone#203]
Hello and thank you for this great project!

Any reasons in particular as to why armv7-unknown-linux-gnueabihf builds in the CI are not added as links to github releases?

**Comment by rmartin16** [comment]
Not necessarily compelling per se...but I use armv7 builds for testing BeeWare compatibility for the Raspberry Pi 2. I ultimately just established a half-baked process to create my own [builds](https://github.com/rmartin16/python-standalone-releases) but it would be much simpler for anyone wanting to use a Pi 2 for it to be available like the other Pythons.
