### ISSUE TITLE
Bump Docker base image

### ISSUE THREAD

**Issue by Xeonacid** [indygreg/python-build-standalone#219]
Hi, I'm adding support for RISC-V.
But https://github.com/indygreg/python-build-standalone/blob/main/cpython-unix/build.cross.Dockerfile#L2 uses a very old image, Debian 9 "Stretch", which has been [EOL in June 30, 2022](https://wiki.debian.org/LTS). And it has no riscv64 cross compiler in apt repo.
Could we bump the base image (and https://github.com/indygreg/python-build-standalone/blob/main/cpython-unix/build.cross.Dockerfile#L24 snapshot OFC) to a newer, in support one?

BTW, https://github.com/indygreg/python-build-standalone/blob/main/cpython-unix/base.Dockerfile#L2 uses an even older one, Debian 8 "Jessie"...

**Comment by indygreg** [comment]
The use of old Debian versions for the build environment is purposefully: it ensures we don't reference too-new glibc symbol versions. (Strictly speaking we could use something like `zig cc` to achieve glibc version targeting without actually compiling against an ancient glibc, but the tried-and-true method of _compile on an older distro/glibc_ is what I went with initially.)

To build out riscv64 support, we can introduce a separate base image (one based on Debian 10 perhaps?) and use it to build riscv64.

**Comment by Xeonacid** [comment]
Thanks!

**Comment by Boring545** [comment]
@Xeonacid  Hello, I am also working on porting to RISCV64. Have you been successful? Could you share some of your experiences?

**Comment by Xeonacid** [comment]
> @Xeonacid Hello, I am also working on porting to RISCV64. Have you been successful? Could you share some of your experiences?

I'm busy with other stuff these days and forgot this... Have no progress right now. Sorry for that. :(
