### ISSUE TITLE
Windows python.exe should support shared libs

### ISSUE THREAD

**Issue by jayvdb** [indygreg/python-build-standalone#22]
The provided `python.exe` is unable to load shared extension libs, defining `Py_NO_ENABLE_SHARED`, and the hacked pyport.h for Windows replaces all the nested extern sym declare alternatives with only the definitions needed to create the .exe.

```h
#define PyAPI_FUNC(RTYPE) __declspec(dllexport) RTYPE
#define PyAPI_DATA(RTYPE) extern __declspec(dllexport) RTYPE
#define PyMODINIT_FUNC __declspec(dllexport) PyObject*
```
i.e. excluding the definitions like `__declspec(dllimport)` needed to build dlls.

This presents a problem especially for built extensions which rely on `cffi` to build, which includes `cryptography` and `gevent` and many more packages in the core of the Python ecosystem.  cffi often isnt needed after the build -- it only needs to exist while running `setup.py` for the package.

afaic, the python.exe inside the distribution is not used *directly* the PyOxidizer app re-packaging, but is used for running pip and the compile scripts.  As a result, `python.exe` can be a shared-enabled binary, and even be a thin exe with shared pythonXY.dll, so that it can be more useful for running pip to build shared libraries.

(Another hack around this would be to also provide `_cffi_backend` as part of the python-build-standalone/ distribution, similar to how PyPy provides it as a core component, but build it into the static python.exe)

**Comment by jayvdb** [comment]
I suspect this project needs to define `MS_NO_COREDLL=1` for its own build, and hopefully that should allow `Py_ENABLE_SHARED=1` to be set.

**Comment by jayvdb** [comment]
If building `_cffi_backend` into the image, be aware of https://bitbucket.org/cffi/cffi/issues/435/msvc-with-external-libffi-support .  I suspect that building `_cffi_backend` into the image wont actually solve the problem, as `cffi` will still attempt to build the custom libffi in.  It's setup.py would need changes to allow PyOxidizer to be handled like PyPy, where the backend isnt built because `cffi` knows it is already provided.

But I have a working solution for cffi which doesnt require changes to the image.  It is a hack, but I am fairly confident there is no other workable approach that will allow using the pip rules with the current `cffi` from PyPI.

**Comment by indygreg** [comment]
This is a complicated problem and you've done a good job explaining it.

Something we may want to consider is distributing multiple versions of object files with variations for `__declspec(dllexport)` and `__declspec(dllimport)` so consumers can link to a static or shared library, as desirable. For PyOxidizer on Windows, I'm strongly considering abandoning the default of static libraries and using DLLs. It is possible to load DLLs from a memory address on Windows. So PyOxidizer could embed DLLs in the produced `.exe` and its custom extension module importer could load them from within the `.exe`. Other Python packaging tools on Windows do this (like PyInstaller IIRC) and this would create the least amount of friction for PyOxidizer users, as Windows wheels containing extension DLLs could easily be used.

**Comment by jayvdb** [comment]
> For PyOxidizer on Windows, I'm strongly considering abandoning the default of static libraries and using DLLs.

Personally, PyOxidizer's main selling point is that it is "static-first" for built extension, which are the backbone of any sizable Python project, and aims to support the three main user OS equally / equivalently.  This tackles one of the problems of Python as it ensures the built extensions are actually compatible, something that including DSOs from wheels doesnt provide.

If you accept wheels with DSOs included on Windows, either you need to accept them also for other platforms, or the pip packaging rule config design of PyOxidizer needs to be heavily redesigned to be platform specific, in order to control pip differently per-platform.  (or the packaging rule config is only used for simple cases, and PyOxidizers of non-trivial projects should use pre-hacked venvs like https://github.com/indygreg/PyOxidizer/pull/199)

fwiw, I have had no extra friction yet with built extensions specifically on Windows, except for libffi/cffi which is a special case as the cause is actually CPython/the Python dist created here (https://github.com/indygreg/python-build-standalone/issues/23).  All platforms very quickly break on built dependencies because a) `simplejson` and `markupsafe` conflict and lots of real scenarios end up depending on both (neat well-tested PR submitted ages ago), and b) lots of packages depend on `gevent` (hacky/buggy workaround provided ages ago, now marked as WIP).  Both are cross-platform problems due to static symbol clashes.   Using DLLs on Windows works around those problems, but then it is solved only for Windows.

The problem is the python.exe shipped in this redist is a) not needed by PyOxidizer repackaging and b) is needed to run pip installs.  The current python.exe fails at (b) for many moderately difficult package with package dependencies.  I have worked around this https://github.com/indygreg/PyOxidizer/pull/199 by using a "real" Windows CPython installation for the build dependencies.

To avoid needing that workaround, this redist only needs to include a python.exe that is more like the normal CPython exe, so that it can be usable for build dependencies.  Ideally that python.exe can be built in the same project as the static libs.  If not, then a separate build invocation may be needed to create the python.exe .
