### ISSUE TITLE
Remove `-shared` from Windows release artifacts

### ISSUE THREAD

**Issue by indygreg** [indygreg/python-build-standalone#237]
Windows static builds were removed in #234.

We preserved the `-shared` target triple suffix for the moment. But it is no longer needed, as its sole role was to disambiguate the static and shared Windows builds. Since there is now only a single variant, no such label is needed.

If we remove the `-shared` suffix, there will be consumers who will need to update code to point to the new value. We may want to consider double publishing the `-shared` and sans-`-shared` release artifacts during a transition period to avoid forced breakage. The download stats can be used to determine when it is safe to stop publishing the `-shared` artifacts.

**Comment by charliermarsh** [comment]
I can take this follow-up.
