### ISSUE TITLE
Find another mirror for xz

### ISSUE THREAD

**Issue by indygreg** [indygreg/python-build-standalone#242]
Due to the xz security incident that broke yesterday, GitHub took the xz project on GitHub offline. https://tukaani.org/xz/xz-5.2.12.tar.gz is redirecting to GitHub release artifacts, which now don't work.

We should find another mirror for xz-5.2.12.tar.gz.

**Comment by indygreg** [comment]
I couldn't find a mirror in 10 minutes of searching. I had a copy sitting on my local machine. So I just uploaded that to an existing GitHub release of this project. https://github.com/indygreg/python-build-standalone/releases/download/20240224/xz-5.2.12.tar.gz

**Comment by bluss** [comment]
Should find another version eventually, since the named release here - 5.2.12 - was also made by the same pseudonym.
