### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by jayvdb** [indygreg/python-build-standalone#25]
This repo should at least have CI, and ideally CD also.

**Comment by indygreg** [comment]
I have patches somewhere that implement CI. However, no free CI system allows us to run long enough to complete a build of all the dependencies. We would need to spend more or leverage intelligent caching of things like compiling GCC/Clang to get it to work.

**Comment by jayvdb** [comment]
Push what you have, and we can collaborate on optimising it?

Re-using artifacts from other projects probably helps. E.g. https://github.com/indygreg/python-build-standalone/issues/17

And e.g. choco / vcpkg / conan packages could be optionally used to speed up builds. Building all from scratch could still be supported, but not verified by CI.

Moving to gitlab is also an option, where we can connect our own runners.

**Comment by indygreg** [comment]
The repository now has CI for macOS and Windows. Linux is going to be a bit harder to implement, as getting compilation caching working isn't trivial.

**Comment by indygreg** [comment]
Linux CI has been implemented.

**Comment by jayvdb** [comment]
Awesome
