### ISSUE TITLE
Support for Python beta releases (3.13)?

### ISSUE THREAD

**Issue by kpfleming** [indygreg/python-build-standalone#263]
I'd like to start using these builds (via Hatch), but I test my software against Python beta releases too. Would it be reasonable to add 3.13 beta releases to the set of builds in this repository?

**Comment by zanieb** [comment]
Yes probably but it's non-trivial. Are you interested in working on it?

**Comment by kpfleming** [comment]
Absolutely. If you know of traps for the unwary, I'm happy to tackle them :-)

**Comment by zanieb** [comment]
I'm still new to the project :) but this was on my list of things to do eventually so feel free to ping me with any questions and we can work through it together.

For some more context, I added https://github.com/indygreg/python-build-standalone/pull/236 in preparation for support for building CPython from GitHub. I was going to get that working on 3.12 before moving to 3.13 / latest so we can continually test against the latest CPython. I presume there are official sources for the 3.13 beta around though so we don't need to go that route.

**Comment by kpfleming** [comment]
Right, there are tarballs for the beta releases so building them should be very similar to building the other ones. I'll give it a try, starting with 3.12 as the baseline.

**Comment by kpfleming** [comment]
I've created #264 which is an optimistic PR assuming that Python 3.13 will build using exactly the same process as 3.12. It will require someone with maintainer privileges to approve the workflows since this is my first contribution to this repository :-)

**Comment by zanieb** [comment]
For others, there's work in progress on this at https://github.com/indygreg/python-build-standalone/pull/264 (Thanks Kevin!)

**Comment by pawamoy** [comment]
It would generally be awesome to have builds for alpha/beta/rc releases of new minor Python versions (currently 3.13, for example). But I understand that this potentially represents a ton of work, making it hard to stay up to date with all the pre-releases before the final one :slightly_smiling_face: So, just wishful thinking! Thanks to all the contributors of this project, it's really helpful :heart:

**Comment by KotlinIsland** [comment]
was this resolved in?
- #319

**Comment by zanieb** [comment]
Yes, but they're not released yet. I'll close once we publish a release with 3.13rc2.

**Comment by sydney-runkle** [comment]
Hi @zanieb,

Any estimate as to when this will be updated?

**Comment by sydney-runkle** [comment]
Hi @zanieb,

Any estimate as to when support might be added here? Thanks!

**Comment by sydney-runkle** [comment]
@zanieb,

Awesome!

Perhaps I'm missing something obvious - when I run `rye pin 3.13rc3`, I get the following:

```
error: unsupported/unknown version for this platform
```

Any recommendations here?

**Comment by kpfleming** [comment]
That's a `rye` issue...

**Comment by zanieb** [comment]
Sounds like the downloads just haven't been updated in Rye yet. It was non-trivial to add support for pre-releases in uv, but they're available there.

**Comment by sydney-runkle** [comment]
>  It was non-trivial to add support for pre-releases in uv, but they're available there.

Awesome, thanks! Will use `uv` then. Apologies for my misplaced question here.
