### ISSUE TITLE
Please archive this repository, Greg.

### ISSUE THREAD

**Issue by kfsone** [indygreg/python-build-standalone#267]
In your blog post you expressed regret at not communicating your change of focus better, closing/archiving the repository would help to convey that.

Thank you for the work and effort you put into building this, but an extra thank you for the blog post explaining the personal and technical reasons for your moving on - resonated deeply with me and also made me rethink what I was planning to do :)

**Comment by charliermarsh** [comment]
I appreciate the sentiment but we don't plan to archive the project! As Greg said in his blog post:

> I... intend for the project to be actively supported for the indefinite future: it has become too important to abandon.

`python-build-standalone` is very much load-bearing and will continue to be supported. We've been stepping in to help @indygreg maintain it.

**Comment by kfsone** [comment]
Are you maintaining a fork or this version? Reading Greg's blog post and seeing no commits for a year makes it look like this repos is dormant.

**Comment by zanieb** [comment]
Hi! There are [commits this year](https://github.com/indygreg/python-build-standalone/commits/main/) and @charliermarsh did the [last release](https://github.com/indygreg/python-build-standalone/releases/tag/20240415) here on this repository.

**Comment by kfsone** [comment]
I was aiming for the PyOxidizer repos, sorry.

**Comment by charliermarsh** [comment]
No prob.
