### ISSUE TITLE
Emit separate debug and release distributions

### ISSUE THREAD

**Issue by jayvdb** [indygreg/python-build-standalone#27]
There is a `--debug` arg for the linux build scripts here.  I've raised https://github.com/indygreg/python-build-standalone/issues/26 for Windows support.

It would be useful to have distribution archives available in https://github.com/indygreg/python-build-standalone/releases for debug and non-debug, with some docs explaining the difference between them.

Then users can initially get their use-case working with the debug builds, and then re-verify it works with the release builds.

**Comment by indygreg** [comment]
Yes, there's no good reason why we couldn't upload debug builds. I believe one of the prior releases even had a Linux debug build uploaded!

**Comment by indygreg** [comment]
We have automated debug builds for Linux and macOS. We're missing debug builds for Windows. Those are tracked by #26. So I'm going to close this out so we don't have separate highly similar issues.
