### ISSUE TITLE
Release for Python 3.12.4?

### ISSUE THREAD

**Issue by kpfleming** [indygreg/python-build-standalone#273]
I'd like to convert a bunch of systems over from built-from-source-locally configurations, and 3.12.4 will be a good opportunity to do that.

**Comment by bulletmark** [comment]
How long does it normally take for a new release here after the latest and greatest Python version is released?

**Comment by zanieb** [comment]
We'll get to this soon. Charlie is out next week.

**Comment by jfcherng** [comment]
Hi there. Any chance we can have that CI retriggered? 😃

**Comment by achimnol** [comment]
Looking forward to the release of 3.12.4!

**Comment by charliermarsh** [comment]
I'll kick this off today.

**Comment by charliermarsh** [comment]
(Sorry for the delay, I forgot about it but saw it in my inbox today.)

**Comment by charliermarsh** [comment]
See: https://github.com/indygreg/python-build-standalone/releases/tag/20240713
