### ISSUE TITLE
install_only builds should be stripped?

### ISSUE THREAD

**Issue by bulletmark** [indygreg/python-build-standalone#277]
The 3.12.3 `x86_64-unknown-linux-gnu` `install_only` build is 251 MB. Stripped using `strip -p --strip-unneeded` it is 81 MB. As discussed [here](https://github.com/indygreg/python-build-standalone/discussions/160) and in issue #275, there is an argument that the normal builds should preserve debug and other symbols but surely the `install_only` builds should be stripped?

**Comment by charliermarsh** [comment]
Personally, I do think this makes sense. Alternatively, we could ship both stripped and unstripped `install_only` builds (but avoid shipping stripped builds for _all_ variants).

**Comment by indygreg** [comment]
As someone who commonly attaches a debugger to random software, it is exceptionally frustrating when you can't load debug symbols for binaries. This significantly inhibits debugging. Especially on PGO+LTO optimized binaries.

As a matter of principle I feel that anyone shipping non closed source software has an obligation to make debug symbols available.

It is not viable for us to run a symbol server for this project (maybe one day GitHub will provide that service: one can only wish). That leaves shipping the symbols as release assets. I prefer having them embedded in binaries. But detached symbols could also work.

I really don't want to ship a symbols/no-symbols variant of each distribution: we have too many release artifacts as it stands.

Perhaps a compromise position is to ship symbols/no-symbols variants for just the `install_only` archives. We keep symbols on `install_only` for backwards compatibility and introduce a new variant - say `install_only_stripped` - that lacks debug symbols.

**Comment by charliermarsh** [comment]
> Perhaps a compromise position is to ship symbols/no-symbols variants for just the `install_only` archives. We keep symbols on `install_only` for backwards compatibility and introduce a new variant - say `install_only_stripped` - that lacks debug symbols.

Yeah, that's where I was leaning too -- roughly what I was trying to say with the second sentence of my previous comment. It seems like a good compromise to me and I'd be happy to own it.

**Comment by charliermarsh** [comment]
I'll give this a try.
