### ISSUE TITLE
Python 3.8 build invalid with missing python3.8m

### ISSUE THREAD

**Issue by mnsanandres** [indygreg/python-build-standalone#29]
I tried building from the source for a Python 3.8 build. I tried either of the following commands:

```
./build-linux.py --musl --libressl --python cpython-3.8
./build-linux.py --optimized --python cpython-3.8
```

The build completed the binary executables link to the python3.8m file which as of [Python 3.8](https://docs.python.org/3/whatsnew/3.8.html#build-and-c-api-changes) appears to have been removed. Also the lib/ folder also contains the invalid ```libpython3.8m.a```.

Is there a proper way to build for 3.8 or is it not yet supported all together.

**Comment by indygreg** [comment]
3.8 is not yet officially supported. But it should be, as it is an officially released Python version and is arguably strictly better than Python 3.7.

**Comment by indygreg** [comment]
I have committed a fix for this locally and it will likely be pushed up today.

**Comment by ntoll** [comment]
@indygreg I've just encountered this problem. I guess I'll have to try again in the morning. Thanks for the (impending) fix..! :+1: :shipit:

**Comment by indygreg** [comment]
I pushed the commits that fix building Python 3.8. I'm not guaranteeing 3.8 works as well as 3.7 does. But at least it builds (at least on Linux and macOS).

**Comment by ntoll** [comment]
@indygreg thanks for pushing.

Out of interest, when you say, "I'm not guaranteeing 3.8 works as well as 3.7 does" - in what ways are you expecting it NOT to work as well. Just asking so I can poke around and test those aspects of the runtime.

:+1: :eyes:

**Comment by ntoll** [comment]
Apologies for the number of comments, but a thought just occurred to me just after submitting the previous comments: might it be helpful to have some sort of test suite that exercises the builds in such a way to guarantee there are no regressions as the project moves to newer versions of Python in the future? What gotchas need to be checked..? Just another safety net of reassurance...

I'd be more than happy to help/contribute if you have ideas (`python-build-standalone` is IMHO a project our community needs so much if Python is to flourish).

**Comment by indygreg** [comment]
`python-build-standalone` reimplements various aspects of Python's build system. So any time we take a version upgrade, we need to audit for changes to Python's build system to see if we need to take any special actions.

As of commits pushed in the past 24 hours, the repository now has a `test-distribution.py` script which can be used to run Python's test harness against the built distribution. I'm pleased to report that all tests pass on macOS and the Linux failures under non-musl builds are minimal. See status at https://python-build-standalone.readthedocs.io/en/latest/status.html.

Even if the tests pass, there can still be bugs at upgrade time. For example, Python may introduce a new extension and we need to teach python-build-standalone how to build it statically.

Fortunately, it is looking like Python 3.8 won't be that much work on macOS and Linux, which is a relief. Look for Python 3.8 packages once Windows is supported and once I've verified PyOxidizer works with those packages. Hopefully in the next week.
