### ISSUE TITLE
CPython 3.12 ARM support

### ISSUE THREAD

**Issue by japborst** [indygreg/python-build-standalone#310]
Would love to see support for cpython-3.12-linux-armv7-gnu so I can run it on my RaspberryPi

**Comment by bulletmark** [comment]
It's already available for RPi. E.g. on mine:
```
$ uname -a
Linux pi2 6.6.47-2-rpi #1 SMP Sun Aug 25 05:32:18 MDT 2024 armv7l GNU/Linux

$ pystand list
3.12.5 @ 20240814 distribution="armv7-unknown-linux-gnueabihf"

$ ~/.local/share/pystand/versions/3.12.5/bin/python -VV
Python 3.12.5 (main, Aug 14 2024, 03:58:19) [GCC 6.3.0 20170516]
```

**Comment by indygreg** [comment]
https://github.com/indygreg/python-build-standalone/releases/download/20240814/cpython-3.12.5+20240814-armv7-unknown-linux-gnueabihf-install_only.tar.gz should work unless I'm missing something.

Please reopen if I'm mistaken.
