### ISSUE TITLE
wrong interpreter path in files

### ISSUE THREAD

**Issue by mcsba** [indygreg/python-build-standalone#32]
python/install/bin/
Python 3.7.7

musl

==> 2to3-3.7 <==
#!/install/bin/python3.7

==> easy_install <==
#!/build/out/python/install/bin/python3

==> easy_install-3.7 <==
#!/build/out/python/install/bin/python3

==> idle3.7 <==
#!/install/bin/python3.7

==> pip <==
#!/build/out/python/install/bin/python3

==> pip3 <==
#!/build/out/python/install/bin/python3

==> pip3.7 <==
#!/build/out/python/install/bin/python3

==> pydoc3.7 <==
#!/install/bin/python3.7

==> pyvenv-3.7 <==
#!/install/bin/python3.7

pgo

==> 2to3-3.7 <==
#!/install/bin/python3.7

==> easy_install <==
#!/build/out/python/install/bin/python3

==> easy_install-3.7 <==
#!/build/out/python/install/bin/python3

==> idle3.7 <==
#!/install/bin/python3.7

==> pip <==
#!/build/out/python/install/bin/python3

==> pip3 <==
#!/build/out/python/install/bin/python3

==> pip3.7 <==
#!/build/out/python/install/bin/python3

==> pydoc3.7 <==
#!/install/bin/python3.7

==> pyvenv-3.7 <==
#!/install/bin/python3.7

**Comment by indygreg** [comment]
I think all the shebangs will reference paths from the build machine.

This is a problem with shebangs: they aren't portable across machines unless files exist in the exact same paths.

I think the best we can do here is document the issue and possibly provide a script in the distribution archive to rewrite shebangs to point to the extracted location of the distribution.

A short-term workaround is to use `python3 -m <module>` to run things. e.g. `python3 -m pip` is effectively identical to running `pip`.

**Comment by mcsba** [comment]
I think it is enough to replace the full path to ./python3
