### ISSUE TITLE
DBM support in builds

### ISSUE THREAD

**Issue by KhazAkar** [indygreg/python-build-standalone#338]
Hello,
I'm playing a little with those build and I can see that only 'dumb' implementation of dbm is available. I get why gdbm is not available, but what about ndbm?

**Comment by tysonclugg** [comment]
Looks like the required header files are missing [as per my comment](https://github.com/indygreg/python-build-standalone/issues/331#issuecomment-2357303933) on #331:
```
…
HAVE_GDBM_H=0
HAVE_GDBM_NDBM_H=0
…
```

**Comment by tysonclugg** [comment]
Also see https://github.com/indygreg/python-build-standalone/issues/91#issuecomment-930695234

**Comment by KhazAkar** [comment]
So basically same situation? Oh well... Thanks!
