### ISSUE TITLE
Turtle (tkinter) causes errors

### ISSUE THREAD

**Issue by ntoll** [indygreg/python-build-standalone#34]
Hi, thanks for this project. It's going to be really useful for some of my projects used in educational settings..!

Using [this build](https://github.com/indygreg/python-build-standalone/releases/download/20200408/cpython-3.7.7-linux64-20200409T0045.tar.zst) I tried to use the `turtle` module. It results in a failure, by the looks of it, a missing file or absence of a path. When running from `python/install/bin`:

```
$ ./python3.7m
Python 3.7.7 (default, Apr  9 2020, 00:46:21) 
[Clang 9.0.1 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import turtle
>>> turtle.forward(100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 6, in forward
  File "/home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/install/lib/python3.7/turtle.py", line 3812, in __init__
    Turtle._screen = Screen()
  File "/home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/install/lib/python3.7/turtle.py", line 3662, in Screen
    Turtle._screen = _Screen()
  File "/home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/install/lib/python3.7/turtle.py", line 3678, in __init__
    _Screen._root = self._root = _Root()
  File "/home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/install/lib/python3.7/turtle.py", line 434, in __init__
    TK.Tk.__init__(self)
  File "/home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/install/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /tools/deps/lib/tcl8.6 /home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/install/lib/tcl8.6 /home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/lib/tcl8.6 /home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/install/library /home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/library /home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/tcl8.6.10/library /home/ntoll/src/mu-editor/Mu-naco/python/linux64/tcl8.6.10/library



This probably means that Tcl wasn't installed properly.
```

I've not tested this yet on Windows or OSX. My feeling is some asset or other isn't getting copied to the correct location when the build is generated. Happy to help in any way I can... got questions, just ask..! Thank you in advance for your help..! :+1:

**Comment by ntoll** [comment]
Worth mentioning that I can reproduce this with simply:

```
$ ./python3.7m
Python 3.7.7 (default, Apr  9 2020, 00:46:21) 
[Clang 9.0.1 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>> window = tkinter.Tk()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/install/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /tools/deps/lib/tcl8.6 /home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/install/lib/tcl8.6 /home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/lib/tcl8.6 /home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/install/library /home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/library /home/ntoll/src/mu-editor/Mu-naco/python/linux64/python/tcl8.6.10/library /home/ntoll/src/mu-editor/Mu-naco/python/linux64/tcl8.6.10/library



This probably means that Tcl wasn't installed properly.
```

**Comment by indygreg** [comment]
Does https://python-build-standalone.readthedocs.io/en/latest/quirks.html#tkinter-tclerror-can-t-find-a-usable-init-tcl answer your question?

**Comment by ntoll** [comment]
@indygreg Aha..! That's fixed it. Apologies for causing noise on the line. I see you've put things on RTD and linked to it from the README. That's going to make finding this sort of thing a LOT easier from a human-readable point of view. Thank you..!

FWIW I'm re-factoring my "Mu" project ~ a code editor for beginner Python programmers (see https://codewith.mu/). Given the educational and cross platform nature of the project, having `turtle` available to teachers and beginner coders is rather important.

**Comment by indygreg** [comment]
I actually discovered an issue with the install layout of the tcl files on Linux/macOS. Once I push a commit I've authored locally, you should no longer need the environment variable workaround on those platforms.

**Comment by ntoll** [comment]
@indygreg nice one. :+1:

As it happens... I've spent part of today scripting a way to download the stand-alone versions of Python so I can build an installer that bundles them for each of our supported platforms. 

Had to find a solution for unzipping `zst` files... oh look what I found: https://pypi.org/project/zstandard/ :smile:
