### ISSUE TITLE
Mechanism to submit security issues

### ISSUE THREAD

**Issue by itamarst** [indygreg/python-build-standalone#348]
Hi, I had a security issue I wanted to report, and there's no mechanism to do it privately at the moment.

**Comment by indygreg** [comment]
Email me. gregory.szorc@gmail.com.

**Comment by itamarst** [comment]
When you have time, let me know if you the thing I sent via email is something you consider to be a problem.

**Comment by zanieb** [comment]
Yes we're addressing it in https://github.com/indygreg/python-build-standalone/pull/350

**Comment by itamarst** [comment]
Thank you! Are you thinking about the broader process issue too? I.e. rebuilding existing Python versions when a new OpenSSL version comes out? (I imagine other dependencies may also be an issue, this just seemed like the most obvious one to check.)

**Comment by zanieb** [comment]
Well, we'll rebuild the latest patch version but we can't rebuild them all because it's too much to build.

And yeah, I'm trying to figure out a better way to get notified and otherwise automated dependency updates. I just manually checked everything and opened >15 PRs but it was pretty tedious.

**Comment by itamarst** [comment]
Oh, yeah, I meant rebuilding latest patch revision only. Older patch revisions will have _Python_ security vulnerabilities too, after all.

**Comment by zanieb** [comment]
Thanks!

**Comment by itamarst** [comment]
Thank you!
