### ISSUE TITLE
Compile/Link static distribution with static C/C++ Run Time Lib

### ISSUE THREAD

**Issue by polkovnikov** [indygreg/python-build-standalone#37]
Would be great if everything in static python distribution is compiled/linked with static CRT. So that libs are really static, not needing to install any extra C/C++ redistributable package in the system.

E.g. in Win/MSVC compile all libs with `/MT` flag instead of `/MD`.

In GCC use `-static`/`-static-libstdc++`/`-static-libgcc` flags for compile. Although maybe static builds in Linux world is not that necessary as in Win, but still will be good.

BTW, at least for MSVC if a lib was compiled statically (with /MT) then final application can use both /MT and /MD and link that library. While if a lib was dynamical (with /MD) then application can't use /MT, there will be link errors. In that sense /MT library is more universal and useful.

**Comment by indygreg** [comment]
This is a legitimate feature request.
