### ISSUE TITLE
Latest release json metadata file out of date

### ISSUE THREAD

**Issue by bulletmark** [indygreg/python-build-standalone#372]
There is a new [20241016](https://github.com/indygreg/python-build-standalone/releases/tag/20241016) release 6 hours ago but the [latest release json](https://raw.githubusercontent.com/indygreg/python-build-standalone/latest-release/latest-release.json) metadata file still points to the old release. I have seen previously that this always updates immediately and automatically so it appears something is broken?

**Comment by zanieb** [comment]
We're doing the releases manually because GitHub Actions is broken for releasing right now — so I need to push the change but building commits is really expensive (i.e., slow) and we have a lot of security updates going through right now so I haven't done it yet.

**Comment by zanieb** [comment]
Oh nevermind it's on a different branch; I can update that now.
