### ISSUE TITLE
Support WinXP

### ISSUE THREAD

**Issue by polkovnikov** [indygreg/python-build-standalone#38]
If possible and not to difficult. Would be great to have static python for XP.

For XP support one needs:
  1. Use Python 3.4 sources, this is the last python version with XP support.
  2. Do needed tweaks in pcbuild+msbuild+vcxproj files. PCBuild folder in sources has different .vcxproj/.props files than in Py 3.7.
  3. Use any MSVC version, 2019 is fine also.
  4. Compile all .c/.cpp files with MSVC `cl` flag `/D_USING_V110_SDK71_`, link all binaries with MSVC `link` flag `/SUBSYSTEM:WINDOWS,5.01` (for win apps) and `/SUBSYSTEM:CONSOLE,5.01` (for console apps).
  5. Also check what versions of libs-dependencies support XP. Or just try to compile and run in XP.

**Comment by indygreg** [comment]
I'm going to make an executive decision to not support this.

If someone wants to maintain a fork of this project to do it, by all means. I just don't think support for Windows XP is worth the ongoing maintenance burden.
