### ISSUE TITLE
Build Python 3.13 non free threaded using mimalloc

### ISSUE THREAD

**Issue by arnabanimesh** [indygreg/python-build-standalone#389]
Build Python 3.13 non free threaded using mimalloc instead of obmalloc/pymalloc

**Comment by arnabanimesh** [comment]
Main reason: The builds in python.org include mimalloc as mentioned in their release notes.

Also, as a minor sidenote, there is a noticeable (although not that much) speed improvement as mentioned in this thread: https://github.com/python/cpython/issues/90815

**Comment by zanieb** [comment]
Okay, thanks!

**Comment by arnabanimesh** [comment]
Oh. Nice.

Although as mentioned in your comment https://github.com/indygreg/python-build-standalone/pull/391#issuecomment-2474723842, it is better to mention it explicitly in my opinion. Mentioning the `--with-mimalloc` flag for non free threaded build is like a test case for ensuring that `mimalloc` support is indeed present when building using CI. Since we are building free threaded builds (which requires `mimalloc`) for all the target platforms anyways, we need to ensure that `mimalloc` is being used for non free threaded builds in those target platforms.

**Comment by zanieb** [comment]
Yeah I'll probably continue my work there regardless.
