### ISSUE TITLE
Minimal builds

### ISSUE THREAD

**Issue by shakfu** [indygreg/python-build-standalone#399]
Cool project, I wish it existed years ago, as I had to roll my own system for my covid-era [py-js](https://github.com/shakfu/py-js) project which required a minimal standalone python to be embedded in a c-based plugin. For this, I had to create a custom python build-system called [builder](https://github.com/shakfu/py-js/tree/main/source/projects/py/builder) to:

- build a standalone python in three statically-linked, dynamically-linked and also framework-based variants.
- remove non-essentials such as tests and irrelevant modules and extensions
- zip the stdlib
- convert absolute dependency references to relative refs

I thought this was useful enough to spin off another fit-for-purpose project: [buildpy](https://github.com/shakfu/buildpy), which does that same as builder but in a much more improved and refined way... this project also includes working c++, golang, and rust versions of `buildpy` for fun as well and WIP Haskell, Swift versions as well.

**Comment by zanieb** [comment]
Is this an advertisement for that project or.. ?

**Comment by shakfu** [comment]
No not "advertizing", "sharing", as in "beer" as in "open-source". :smile:  Also commenting on two projects (this widely used one and my little-known `buildpy` project) independently trying to achieve the roughly similar objective of providing "standalone" python builds, and I'm highlighting that in my case, I was also highly motivated by the need to minimize the size of python builds (for use in a compiled, relocatable plugin context where I had to embed a full python interpreter). Also noting some of the techniques which could be used here if there's interest to minimize builds further: zipping the stdlib, removing redundant or soon-to-be-deprecated modules, extensions, etc..

**Comment by zanieb** [comment]
Thanks, that context is helpful. From just the first post (and the title), I was genuinely unsure of what your goal was and consequently how to reply or engage.

So, specifically, the thought here is that there's a use-case for _minimized_ builds (i.e., in size) and we may find inspiration for that in the `buildpy` project?

As an aside: it's cool that you have multi-language build support

**Comment by shakfu** [comment]
> Thanks, that context is helpful. From just the first post (and the title), I was genuinely unsure of what your goal was and consequently how to reply or engage.

Fair enough.

> So, specifically, the thought here is that there's a use-case for _minimized_ builds (i.e., in size) and we may find inspiration for that in the `buildpy` project?

Exactly.

> As an aside: it's cool that you have multi-language build support

Thanks 😄

**Comment by indygreg** [comment]
PyOxidizer would allow you to take the distributions from this project and produce a more minimal `python` executable if you wanted. See https://gregoryszorc.com/docs/pyoxidizer/main/pyoxidizer_packaging_python_executable.html.

There's also the PyOxy project, which essentially did this for you and released the binaries as standalone single file Python distributions. https://gregoryszorc.com/docs/pyoxidizer/main/pyoxy.html.

Both projects are in a zombie state. But there's some good ideas there worth stealing.

**Comment by shakfu** [comment]
Thanks @indygreg

Appreciate the links and background behind PyOxidizer and PrOxy. Will check them out for sure. It's a pity they are as you said in a zombie state, but I do understand what a pain it is to maintain given changes in python version.
