### ISSUE TITLE
Missing Non-Freethreaded Version for Python 3.13 and Python 3.11.11 Release

### ISSUE THREAD

**Issue by merajhashemi** [indygreg/python-build-standalone#407]
I’ve noticed a couple of things related to Python version availability when using uv, and I’m not entirely sure if this is the right place to report it or if it might belong in the uv repository. Since both projects are soon to be managed by Astral, I thought it might be worth mentioning here first.

1. The non-freethreaded version of Python 3.13 does not appear to be available for download.
2. Even though Python 3.11.11 has been released, and I saw that #400 for adding it was merged (@zanieb), it is still not listed as an available version.

When I run:
```bash
uv python list --all-versions
```

I see the following versions listed, but neither the non-freethreaded Python 3.13 nor Python 3.11.11 appear:
```bash
cpython-3.13.0+freethreaded-linux-x86_64-gnu    <download available>
cpython-3.12.7-linux-x86_64-gnu                 <download available>
cpython-3.12.6-linux-x86_64-gnu                 <download available>
cpython-3.12.5-linux-x86_64-gnu                 <download available>
cpython-3.12.4-linux-x86_64-gnu                 <download available>
cpython-3.12.3-linux-x86_64-gnu                 <download available>
cpython-3.12.2-linux-x86_64-gnu                 <download available>
cpython-3.12.1-linux-x86_64-gnu                 <download available>
cpython-3.12.0-linux-x86_64-gnu                 <download available>
cpython-3.11.10-linux-x86_64-gnu                <download available>
...
```

Would you be able to confirm whether this behavior is expected—i.e., it might require adjustments on my end—or if it is a bug?

---
**Environment**
Operating System: Ubuntu 22.04.3 LTS
uv version: 0.5.6

**Comment by zanieb** [comment]
I'm going to transfer this over to uv because these are not problems here.

**Comment by zanieb** [comment]
You can install 3.13.0 — the `--all-versions` output must have a bug. `uv python install 3.13` should install the non-freethreaded variant.

Access to the latest versions, like 3.11.1, requires a new uv release. That's in progress in https://github.com/astral-sh/uv/pull/9663

**Comment by zanieb** [comment]
Fixing that display bug in https://github.com/astral-sh/uv/pull/9669
