### ISSUE TITLE
Unable to get libXau from its mirror

### ISSUE THREAD

**Issue by jwarner112** [indygreg/python-build-standalone#45]
Received an error (FTP -> ConnectionRefused) when trying to obtain `libXau-1.0.7.tar.gz` from [its provided mirror](https://github.com/indygreg/python-build-standalone/blob/master/pythonbuild/downloads.py#L174).

Replaced that mirror with [Xorg's primary mirror in Oregon](ftp://ftp.freedesktop.org/pub/xorg/X11R7.7/src/lib/libXau-1.0.7.tar.gz) to circumvent. Considered a patch that turns `entry["url"]` into `entry["urls"]` and handles this failure by trying the next mirror in a list, but the handling is a bit bizarre in `urllib` and `ftplib`.

**Comment by indygreg** [comment]
I committed a patch for this locally a few days ago but haven't pushed it yet.

**Comment by jwarner112** [comment]
Fantastic to hear, thank you! And great work, by the way.

**Comment by indygreg** [comment]
I just pushed 921d37fb8a8889064e03ae09e3e202c9c00a6f92, which fixes this.
