### ISSUE TITLE
cpython linux arm support

### ISSUE THREAD

**Issue by thetoolz** [indygreg/python-build-standalone#60]
cpython is really great
wish there was a
cpython linux for arm architecture devices

**Comment by thetoolz** [comment]
for windows arm64 support
https://github.com/jay0lee/CPython-Windows-ARM64

**Comment by thetoolz** [comment]
cpython builder with arm64 support
https://github.com/travis-ci/cpython-builder

**Comment by indygreg** [comment]
I just pushed support for building CPython 3.9 for aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabi, armv7-unknown-linux-gnueabihf, mips-unknown-linux-gnu, mipsel-unknown-linux-gnu, and s390x-unknown-linux-gnu.

I consider support alpha quality at the moment. The builds are completely untested.

Please file new issues tracking problems with the Python builds or requests for building specific targets.
