### ISSUE TITLE
add python 3.9.1 builds

### ISSUE THREAD

**Issue by hemnstill** [indygreg/python-build-standalone#63]
Release Date: Dec. 7, 2020

https://www.python.org/downloads/release/python-391/

Found in code:
```
    "cpython-3.9": {
        "url": "https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tar.xz",
        "size": 18897104,
        "sha256": "991c3f8ac97992f3d308fefeb03a64db462574eadbff34ce8bc5bb583d9903ff",
        "version": "3.9.1"
```

But not found in releases.

**Comment by indygreg** [comment]
Code in `main` already builds 3.9.1. I just haven't made an official release yet. However, CI is producing usable artifacts that you can use. Browse to the `Actions` tab and download an artifact containing the collection of tarball distributions for a given platform. e.g. https://github.com/indygreg/python-build-standalone/suites/1726833059/artifacts/32686861 is Linux distributions.

**Comment by hemnstill** [comment]
Thanks for the tip!

**Comment by indygreg** [comment]
A new release has been published: https://github.com/indygreg/python-build-standalone/releases/tag/20210103
