### ISSUE TITLE
Failure in creating build venv due to pip requirement

### ISSUE THREAD

**Issue by hakostra** [indygreg/python-build-standalone#67]
On a fresh Linux Mint 20 system, with the most recent master version of this git repo (e40c9c7), i get the following failure when running `build-linux.py`:

```
Collecting pip>=20.1
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    pip>=20.1 from https://files.pythonhosted.org/packages/54/eb/4a3642e971f404d69d4f6fa3885559d67562801b99d7592487f1ecc4e017/pip-20.3.3-py2.py3-none-any.whl#sha256=fab098c8a1758295dd9f57413c199f23571e8fde6cc39c22c78c961b4ac6286d (from pip-tools==5.5.0->-r /home/hakostra/MGLET/kmt_devtools/python-build-standalone/requirements.txt (line 66))
```

The problem is mitigated by running:
```
pip-compile --generate-hashes --allow-unsafe --output-file=requirements.txt requirements.txt.in
```
i.e. with the `--allow-unsafe` flag to regenerate the requirements.txt

python version: 3.8.5
pip version: 20.0.2
pip-compile version: 5.5.0

I am not sure if this is a problem with my setup (i.e. more or less the stock packages that come with Ubuntu 20.04 / Linux mint 20) or another problem. Anyways, the build process seems to proceed fine when the above mentioned problem is resolved.

**Comment by indygreg** [comment]
Thanks for reporting this.

The presence of `pip-tools` in the requirements file is a bit dubious. I'm pretty sure it isn't required. So I'll be removing it and with it the dependency on the `pip` package that is causing this issue.
