### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by polkovnikov** [indygreg/python-build-standalone#69]
Although Python 3.10 is still in testing version 3.10.0a5, would be great to incorporate it early into your system!

Mainly because of long-awaited new feature which can be enabled by `#define EXPERIMENTAL_ISOLATED_SUBINTERPRETERS 1`. This feature allows to use fully isolated interpreters within one process. It means no more global GIL! Each interpreter now has local GIL. Hence now Python can be multi-core, thus boosting multi-threaded scripts many times (as many cores there are)!

Different interpreters are isolated and they can't (probably) share objects between each other except for passing serialized (pickled) form of objects between each other. Still each C/C++ thread can run a separate interpreter for parallel algorithms that need not too much of data interaction between threads. Basically this feature allows achieving same thing as with `multiprocessing` module but within one process instead of many processes.

This feature was developed for several years and now it became alive. It needed to hand-modify around 1500 global static variables to make them thread-local scope.

Would be great to become first early alpha testers of this feature. I used Python C API in my C++ code a lot and thrilled of using now all the CPU cores within one process.

If you think that for some reason non-release version of Python 3.10 is not allowed for your system (although you can make some switch like `--python experimental-cpython-3.10`) then you can leave this feature request (issue) open till 3.10 becomes a release, and probably it will become not far in the future. But if you decide to support it then don't forget to enable `#define` mentioned above.

**Comment by polkovnikov** [comment]
@indygreg Thanks for quick response and commit! I'll start from Unix.

Can't wait to have 3.10 on Windows too, because Windows is my main PC OS and main initial development/testing platform. Of cause do this in your own pace later.

**Comment by indygreg** [comment]
`main` now has full support for CPython 3.10 (currently 3.10.0rc2) on all supported platforms. We should be ready to ship 3.10.0 when it is released.

As for `--with-experimental-isolated-subinterpreters`, this is not something we can enable by default as it changes too many behaviors of how Python is built. But I'm receptive to adding a build configuration for it. If you would still like this feature, please file a new issue to track it.

**Comment by polkovnikov** [comment]
@indygreg Yes, exactly, I wanted isolated subinterpreters to be just some configurable option of your build srcipt that is not enabled by default.

Also, I'm not sure, but maybe final release of Python 3.10 will enable this feature by default in their binary releases on python.org.

**Comment by polkovnikov** [comment]
@indygreg Hooray! A day ago first version of Python 3.10.0 was officially released, [here](https://www.python.org/downloads/)!

So you can now officially use this release in your builds. Also don't forget to see my [other feature request](https://github.com/indygreg/python-build-standalone/issues/92) about supporting isolated sub-interpreters in Python 3.10 build.
