### ISSUE TITLE
Tkinter module missing in build

### ISSUE THREAD

**Issue by lawik** [indygreg/python-build-standalone#7]
As reported at https://github.com/indygreg/PyOxidizer/issues/25 the tkinter stuff is missing in the builds. Having it would be great for small GUI utils.

Also it makes the thing I'm building crash. So no bueno :)

**Comment by Tipuch** [comment]
If I'm not mistaken tl/tk is missing specifically for OS X builds: I don't have a mac but I think these resources may help you (the download links you used for linux should also work for OS X according to their download page). 
- https://blog.tcl.tk/12987#pagetocbac4642b

**Comment by lawik** [comment]
From what @indygreg said this would simply be due to tkinter not being something he included as he had bigger fish to fry. I didn't have a problem building, I had only had a problem running. So it is probably missing tl/tk. But it doesn't even have the tkinter module so it is a bit moot :)

**Comment by Tipuch** [comment]
I'm sorry, this message was addressed to the maintainer, based on what I gathered from the current code.

**Comment by indygreg** [comment]
I just pushed a handful of commits that build the `_tkinter` extension on Linux. I have some partial patches for Windows support. And macOS support should be easier than Linux.

I'm not yet comfortable that the extension works correctly in all cases. I believe there's still a problem where the `.tcl` sources need to be distributed with the final binary.

But at least the hurdle of getting the extension module compiled and running from a self-contained executable is cleared...

**Comment by Schmetzler** [comment]
Is there a workaround to still use tkinter with pyoxidizer?
Would be great.  or I have to switch to pyinstaller again (but the loading time is horrible).
Currently I would need it for Windows.

**Comment by Schmetzler** [comment]
Is there a workaround to still use tkinter with pyoxidizer?
Would be great. or I have to switch to pyinstaller again (but the loading time is horrible).
Currently I would need it for Windows.

**Comment by indygreg** [comment]
I have Windows support for tkinter in the shared library distribution flavor, which will be published shortly.

**Comment by indygreg** [comment]
I've confirmed that `tkinter` works for macOS, Windows shared, and the non-musl Linux distributions. So we have support on all the supported platforms.

Getting it to work on the static build variants is considerably more work and I'm not sure it is worth it at this time. If those are features you would like, please file a new issue tracking each distinct platform and we can look into things in those issues.
