### ISSUE TITLE
Last version with Windows 7 support?

### ISSUE THREAD

**Issue by gavanderhoorn** [indygreg/python-build-standalone#78]
While the [docs](https://python-build-standalone.readthedocs.io/en/latest/running.html#windows) are fairly clear about minimum versions of Windows supported, the text seems to leave room for the interpretation that Windows 7 *was* supported at some point, but that support was dropped.

Is that interpretation correct, or was Windows 7 never supported?

If it was supported: which release would be the latest to be runnable on a Windows 7 OS?

(I realise Win7 is old and unsupported, but unfortunately I'm dealing with a system which cannot be updated, so I'm stuck)

**Comment by gavanderhoorn** [comment]
fwiw: `cpython-3.7.6-windows-amd64-static-20200216T2300.tar.zst` seems to work for me so far on the Win7 installation I'm targetting.

Haven't tried any of the newer versions yet.

**Comment by indygreg** [comment]
The Windows static builds likely have various issues. It depends on what Python extensions you run. It is best to stick with the shared distributions, as they are built similarly to the official www.python.org Windows builds.

As for Windows 7 support, it was likely dropped by https://github.com/indygreg/python-build-standalone/commit/f163c2e1c581afe315aa524178751ed4ed0ff1f4. If you reverse that patch, it is likely that Python 3.8 builds will still work on Windows 7. However, Python 3.9 will not work, as that support was dropped by CPython upstream.

If this answers your questions, feel free to close this issue.

**Comment by gavanderhoorn** [comment]
Thanks for your response, and apologies for my delayed one.

I was indeed never able to get the static builds to work -- or at least, they kept crashing at "random" points.

**Comment by silverjam** [comment]
FWIW I think I was able to restore Windows 7 support with this patch: https://github.com/swift-nav/python-build-standalone/commit/feb0f4494d9710dd293e98e8b9af502f305242d5 -- the interpreter launches at least, not sure what other testing is needed though.

**Comment by silverjam** [comment]
@gavanderhoorn if you'd like to test out a build, you can grab it from the GitHub Actions artifacts here: https://github.com/swift-nav/python-build-standalone/actions/runs/1225481877

@indygreg if this works, is there any reason not to merge https://github.com/swift-nav/python-build-standalone/commit/feb0f4494d9710dd293e98e8b9af502f305242d5?

**Comment by gavanderhoorn** [comment]
@silverjam: thanks. I'll see if I can find some time to test it out.
