### ISSUE TITLE
Could not open PYTHONSTARTUP

### ISSUE THREAD

**Issue by Wissperwind** [indygreg/python-build-standalone#81]
Hi,
I am trying your portable python on opensuse. But it says the error below.
Does someone know why?

```
gda-opensuse-01 install/bin% ls
2to3  2to3-3.9  idle3  idle3.9  pip  pip3  pip3.9  pydoc3  pydoc3.9  python3  python3.9  python3.9-config  python3-config
gda-opensuse-01 install/bin% ./python3
Python 3.9.5 (default, May  6 2021, 19:23:49)
[Clang 12.0.0 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
Could not open PYTHONSTARTUP
FileNotFoundError: [Errno 2] No such file or directory: '/etc/pythonstart'
>>> print("Hi")
Hi
>>> exit()

```

**Comment by indygreg** [comment]
`PYTHONSTARTUP` is an environment variable that allows you to execute an arbitrary Python file when the interpreter starts. See https://docs.python.org/3/using/cmdline.html#envvar-PYTHONSTARTUP.

The distributions from this project should not set/define a default value for `PYTHONSTARTUP`. So if you are seeing references to it, something on your machine is setting the environment variable.

Normally I'd close this issue as not actionable for this project. But I'd like to understand where the reference is coming from and why it isn't working so we can address (potentially just through documentation) a potential compatibility issue with a known runtime environment.

**Comment by indygreg** [comment]
I don't believe this issue is actionable so I am closing it.
